-- ============================================================
-- Supabase / PostgreSQL Migration: Spend Budgets Table
-- ============================================================

CREATE TABLE IF NOT EXISTS public.spend_budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount DECIMAL(12, 2) NOT NULL,
    type VARCHAR(20) NOT NULL CHECK (type IN ('Fund', 'Expense', 'Income')),
    note TEXT,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_spend_budgets_user ON public.spend_budgets(user_id);
CREATE INDEX IF NOT EXISTS idx_spend_budgets_date ON public.spend_budgets(date DESC);
CREATE INDEX IF NOT EXISTS idx_spend_budgets_created ON public.spend_budgets(created_at DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE public.spend_budgets ENABLE ROW LEVEL SECURITY;

-- RLS Policies
DROP POLICY IF EXISTS "Allow users to select their spend_budgets" ON public.spend_budgets;
CREATE POLICY "Allow users to select their spend_budgets" ON public.spend_budgets
    FOR SELECT
    USING (auth.uid() IS NULL OR user_id = auth.uid() OR user_id IS NULL);

DROP POLICY IF EXISTS "Allow users to insert spend_budgets" ON public.spend_budgets;
CREATE POLICY "Allow users to insert spend_budgets" ON public.spend_budgets
    FOR INSERT
    WITH CHECK (auth.uid() IS NULL OR user_id = auth.uid() OR user_id IS NULL);

DROP POLICY IF EXISTS "Allow users to update their spend_budgets" ON public.spend_budgets;
CREATE POLICY "Allow users to update their spend_budgets" ON public.spend_budgets
    FOR UPDATE
    USING (auth.uid() IS NULL OR user_id = auth.uid() OR user_id IS NULL);

DROP POLICY IF EXISTS "Allow users to delete their spend_budgets" ON public.spend_budgets;
CREATE POLICY "Allow users to delete their spend_budgets" ON public.spend_budgets
    FOR DELETE
    USING (auth.uid() IS NULL OR user_id = auth.uid() OR user_id IS NULL);
