-- ============================================================
-- Supabase / PostgreSQL Migration: Categories & Transactions
-- ============================================================

-- 0. Create ENUM type for Transaction / Category Type
DO $$ BEGIN
    CREATE TYPE transaction_type AS ENUM ('Expense', 'Income');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 1. Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    type transaction_type NOT NULL DEFAULT 'Expense',
    icon VARCHAR(50) DEFAULT '🏷️',
    color_code VARCHAR(10) DEFAULT '#FF6B6B',
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    is_default BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Ensure all required columns exist in public.categories even if table already existed
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS type transaction_type NOT NULL DEFAULT 'Expense';
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS icon VARCHAR(50) DEFAULT '🏷️';
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS color_code VARCHAR(10) DEFAULT '#FF6B6B';
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS is_default BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Index for categories
CREATE INDEX IF NOT EXISTS idx_categories_user ON public.categories(user_id);
CREATE INDEX IF NOT EXISTS idx_categories_is_default ON public.categories(is_default);

-- 2. Prevent deletion of default categories via Trigger
CREATE OR REPLACE FUNCTION public.prevent_default_category_delete()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.is_default = true THEN
        RAISE EXCEPTION 'Default categories cannot be deleted.';
    END IF;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS prevent_default_category_delete_trigger ON public.categories;
CREATE TRIGGER prevent_default_category_delete_trigger
BEFORE DELETE ON public.categories
FOR EACH ROW
EXECUTE FUNCTION public.prevent_default_category_delete();

-- 3. Transactions Table
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL,
    type transaction_type NOT NULL DEFAULT 'Expense',
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    note TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index for transactions
CREATE INDEX IF NOT EXISTS idx_transactions_user ON public.transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_category ON public.transactions(category_id);
CREATE INDEX IF NOT EXISTS idx_transactions_date ON public.transactions(date DESC);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- Categories RLS Policies
DROP POLICY IF EXISTS "Allow users to view categories" ON public.categories;
CREATE POLICY "Allow users to view categories" ON public.categories
    FOR SELECT
    USING (is_default = true OR user_id = auth.uid() OR user_id IS NULL);

DROP POLICY IF EXISTS "Allow users to insert categories" ON public.categories;
CREATE POLICY "Allow users to insert categories" ON public.categories
    FOR INSERT
    WITH CHECK (auth.uid() IS NOT NULL AND user_id = auth.uid() AND is_default = false);

DROP POLICY IF EXISTS "Allow users to update categories" ON public.categories;
CREATE POLICY "Allow users to update categories" ON public.categories
    FOR UPDATE
    USING (user_id = auth.uid() AND is_default = false);

DROP POLICY IF EXISTS "Allow users to delete categories" ON public.categories;
CREATE POLICY "Allow users to delete categories" ON public.categories
    FOR DELETE
    USING (user_id = auth.uid() AND is_default = false);

-- Transactions RLS Policies
DROP POLICY IF EXISTS "Allow users to select their transactions" ON public.transactions;
CREATE POLICY "Allow users to select their transactions" ON public.transactions
    FOR SELECT
    USING (user_id = auth.uid() OR user_id IS NULL);

DROP POLICY IF EXISTS "Allow users to insert transactions" ON public.transactions;
CREATE POLICY "Allow users to insert transactions" ON public.transactions
    FOR INSERT
    WITH CHECK (auth.uid() IS NOT NULL AND user_id = auth.uid());

DROP POLICY IF EXISTS "Allow users to update their transactions" ON public.transactions;
CREATE POLICY "Allow users to update their transactions" ON public.transactions
    FOR UPDATE
    USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Allow users to delete their transactions" ON public.transactions;
CREATE POLICY "Allow users to delete their transactions" ON public.transactions
    FOR DELETE
    USING (user_id = auth.uid());

-- 5. Insert Default Categories if none exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM public.categories WHERE is_default = true) THEN
        INSERT INTO public.categories (name, type, icon, color_code, is_default, user_id)
        VALUES
            ('Housing', 'Expense', '🏠', '#3B82F6', true, NULL),
            ('Groceries', 'Expense', '🛒', '#F59E0B', true, NULL),
            ('Dining Out', 'Expense', '🍔', '#F97316', true, NULL),
            ('Transport', 'Expense', '🚗', '#A855F7', true, NULL),
            ('Health', 'Expense', '💊', '#F43F5E', true, NULL),
            ('Travel', 'Expense', '✈️', '#06B6D4', true, NULL),
            ('Utilities', 'Expense', '💡', '#EAB308', true, NULL),
            ('Shopping', 'Expense', '🛍️', '#6366F1', true, NULL);
    END IF;
END $$;
